src/Entity/SdSport.php
<?php

namespace App\Entity;

use App\Entity\SdPratique;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\SdSportRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=SdSportRepository::class)
 * @UniqueEntity(fields={"nom_sport"}, message="Il semble que ce sport est déjà dans la liste !")
 */
class SdSport
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="nom_sport", type="string", length=320, unique=true)
     */
    private $nom_sport;

    public function __toString(){
        return $this->nom_sport;
    }

    /**
     * @ORM\OneToMany(targetEntity=SdPratique::class, mappedBy="id_sport")
     */
    private $id_sport;

    public function __construct()
    {
        $this->id_sport = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSport(): ?string
    {
        return $this->nom_sport;
    }

    public function setNomSport(string $nom_sport): self
    {
        $this->nom_sport = $nom_sport;

        return $this;
    }

    /**
     * @return Collection|SdPratique[]
     */
    public function getIdSport(): Collection
    {
        return $this->id_sport;
    }

    public function addIdSport(SdPratique $idSport): self
    {
        if (!$this->id_sport->contains($idSport)) {
            $this->id_sport[] = $idSport;
            $idSport->setIdSport($this);
        }

        return $this;
    }

    public function removeIdSport(SdPratique $idSport): self
    {
        if ($this->id_sport->removeElement($idSport)) {
            // set the owning side to null (unless already changed)
            if ($idSport->getIdSport() === $this) {
                $idSport->setIdSport(null);
            }
        }

        return $this;
    }
}

src/Form/SdSportType.php
<?php

namespace App\Form;

use App\Entity\SdSport;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class SdSportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_sport', EntityType::class, [
                'class' => SdSport::class,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SdSport::class,
        ]);
    }
}

src/Controller/SdSportController.php
<?php

namespace App\Controller;

use App\Entity\SdSport;
use App\Form\SdSportType;
use App\Repository\SdSportRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/sd/sport")
 */
class SdSportController extends AbstractController
{
    /**
     * @Route("/", name="sd_sport_index", methods={"GET"})
     */
    public function index(SdSportRepository $sdSportRepository): Response
    {
        return $this->render('sd_sport/index.html.twig', [
            'sd_sports' => $sdSportRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="sd_sport_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $sdSport = new SdSport();
        $form = $this->createForm(SdSportType::class, $sdSport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($sdSport);
            $entityManager->flush();

            return $this->redirectToRoute('sd_sport_index');
        }

        return $this->render('sd_sport/new.html.twig', [
            'sd_sport' => $sdSport,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sd_sport_show", methods={"GET"})
     */
    public function show(SdSport $sdSport): Response
    {
        return $this->render('sd_sport/show.html.twig', [
            'sd_sport' => $sdSport,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="sd_sport_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, SdSport $sdSport): Response
    {
        $form = $this->createForm(SdSportType::class, $sdSport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('sd_sport_index');
        }

        return $this->render('sd_sport/edit.html.twig', [
            'sd_sport' => $sdSport,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sd_sport_delete", methods={"DELETE"})
     */
    public function delete(Request $request, SdSport $sdSport): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sdSport->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($sdSport);
            $entityManager->flush();
        }

        return $this->redirectToRoute('sd_sport_index');
    }
}

templates/sd_sport/_delete_form.html.twig
<form method="post" action="{{ path('sd_sport_delete', {'id': sd_sport.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sd_sport.id) }}">
    <button class="btn">Delete</button>
</form>

templates/sd_sport/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/sd_sport/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SdSport{% endblock %}

{% block body %}
    <h1>Edit SdSport</h1>

    {{ include('sd_sport/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('sd_sport_index') }}">back to list</a>

    {{ include('sd_sport/_delete_form.html.twig') }}
{% endblock %}

templates/sd_sport/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SdSport index{% endblock %}

{% block body %}
    <h1>SdSport index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_sport</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for sd_sport in sd_sports %}
            <tr>
                <td>{{ sd_sport.id }}</td>
                <td>{{ sd_sport.nomSport }}</td>
                <td>
                    <a href="{{ path('sd_sport_show', {'id': sd_sport.id}) }}">show</a>
                    <a href="{{ path('sd_sport_edit', {'id': sd_sport.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('sd_sport_new') }}">Create new</a>
{% endblock %}

templates/sd_sport/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New SdSport{% endblock %}

{% block body %}
    <h1>Create new SdSport</h1>

    {{ include('sd_sport/_form.html.twig') }}

    <a href="{{ path('sd_sport_index') }}">back to list</a>
{% endblock %}

templates/sd_sport/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SdSport{% endblock %}

{% block body %}
    <h1>SdSport</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sd_sport.id }}</td>
            </tr>
            <tr>
                <th>Nom_sport</th>
                <td>{{ sd_sport.nomSport }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('sd_sport_index') }}">back to list</a>

    <a href="{{ path('sd_sport_edit', {'id': sd_sport.id}) }}">edit</a>

    {{ include('sd_sport/_delete_form.html.twig') }}
{% endblock %}